### ISSUE TITLE
Lab Feedback from testing

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/pyats-labs#1]
Consolidated list of feedback from running lab

* Cant' `virl console` to routers (not sure if it matters, but as a virlutils users, I wanted to see what was going on
* `make test` failing to start container.  Needed to log out, then back in to have group add to Docker work 
* After that log out/in, was able to start container, but tests are erring.  See first comment on issue for errors 

In general I think the lab is a good quick introduction to PyATS, and running a working test (once that is fixed) has some value.  But I don't feel like I come away from the lab really feeling like I "know" anything about how to use PyATS.  Some suggestions: 

* Just having links to the DevDocs isn't enough.  Would be good to have some short descriptions of the key parts of the topology file and test code 
* Just reading through the autogenerated topology and provided job and scripts wasn't' enough to have me really understand what is going on, and I definitely don't feel like I could update the tests and info to add another interface or device.  
  * More comments in the code might help... 
  * But I think walking the user through creating the files from scratch, explaining why each bit is needed is going to be important to actually have clarity 
    * As an example, look at this lab: https://learninglabs.cisco.com/modules/intro-device-level-interfaces/intro-netconf/step/4 

If you want to keep this lab this simple, then I'd suggest immediately working on a new lab "Deconstructing the PyATS Tests" or something like that title, where you dive in deeper so people can actually learn more about how to use it.  

Happy to chat more.

**Comment by hpreston** [comment]
```bash
[admin@localhost pyats-ios-sample]$ make test
mkdir -p .pyATS
docker run -it --rm -v /home/admin/pyats-ios-sample:/tests ciscotestautomation/pyats bash /tests/run_tests.sh
[Entrypoint] Starting pyATS Docker Image ...
[Entrypoint] Workspace Directory: /pyats
[Entrypoint] Activating workspace
2018-05-16T21:55:40: %EASYPY-INFO: Starting job run: pyats_ios_example_job
2018-05-16T21:55:40: %EASYPY-INFO: Runinfo directory: /pyats/runinfo/pyats_ios_example_job.2018May16_21:55:39
2018-05-16T21:55:40: %EASYPY-INFO: --------------------------------------------------------------------------------
2018-05-16T21:55:40: %EASYPY-INFO: Testbed file /tests/default_testbed.yaml exists and is readable.
2018-05-16T21:55:40: %EASYPY-INFO: Starting task execution: __task1
2018-05-16T21:55:40: %EASYPY-INFO:     test harness = ats.aetest
2018-05-16T21:55:40: %EASYPY-INFO:     testscript   = /tests/pyats_ios_example.py
2018-05-16T21:55:40: %AETEST-INFO: Starting common setup
2018-05-16T21:55:40: %AETEST-INFO: Starting subsection check_topology
2018-05-16T21:55:40: %AETEST-INFO: The result of subsection check_topology is => PASSED
2018-05-16T21:55:40: %AETEST-INFO: Starting subsection establish_connections
2018-05-16T21:55:40: %AETEST-INFO: STEP 1: Connecting to Router-1

2018-05-16T21:55:40: %UNICON-INFO: +++ initializing context +++

2018-05-16T21:55:40: %UNICON-INFO: +++ initializing state_machine +++

2018-05-16T21:55:40: %UNICON-INFO: +++ initializing services +++

2018-05-16T21:55:40: %UNICON-INFO: adding service  send   :  <unicon.plugins.generic.service_implementation.Send object at 0x7fa6e9968198>

2018-05-16T21:55:40: %UNICON-INFO: adding service  sendline   :  <unicon.plugins.generic.service_implementation.Sendline object at 0x7fa6e9968c88>

2018-05-16T21:55:40: %UNICON-INFO: adding service  expect   :  <unicon.plugins.generic.service_implementation.Expect object at 0x7fa6e9968b00>

2018-05-16T21:55:40: %UNICON-INFO: adding service  execute   :  <unicon.plugins.generic.service_implementation.Execute object at 0x7fa6e9968ba8>

2018-05-16T21:55:40: %UNICON-INFO: adding service  config   :  <unicon.plugins.generic.service_implementation.Config object at 0x7fa6e9968a20>

2018-05-16T21:55:40: %UNICON-INFO: adding service  configure   :  <unicon.plugins.generic.service_implementation.Configure object at 0x7fa6e9968ac8>

2018-05-16T21:55:40: %UNICON-INFO: adding service  enable   :  <unicon.plugins.generic.service_implementation.Enable object at 0x7fa6e9968b38>

2018-05-16T21:55:40: %UNICON-INFO: adding service  disable   :  <unicon.plugins.generic.service_implementation.Disable object at 0x7fa6e9968c18>

2018-05-16T21:55:40: %UNICON-INFO: adding service  reload   :  <unicon.plugins.generic.service_implementation.Reload object at 0x7fa6e9968d30>

2018-05-16T21:55:40: %UNICON-INFO: adding service  ping   :  <unicon.plugins.generic.service_implementation.Ping object at 0x7fa6e9968da0>

2018-05-16T21:55:40: %UNICON-INFO: adding service  copy   :  <unicon.plugins.generic.service_implementation.Copy object at 0x7fa6e9968e10>

2018-05-16T21:55:40: %UNICON-INFO: adding service  expect_log   :  <unicon.plugins.generic.service_implementation.ExpectLogging object at 0x7fa6e9968e80>

2018-05-16T21:55:40: %UNICON-INFO: adding service  log_user   :  <unicon.plugins.generic.service_implementation.LogUser object at 0x7fa6e9968eb8>

2018-05-16T21:55:40: %UNICON-INFO: +++ connection to spawn_command: telnet 10.10.20.160 17000, id: 140354860417544 +++

2018-05-16T21:55:40: %UNICON-INFO: connection to ios1

2018-05-16T21:55:40: %UNICON-INFO: telnet 10.10.20.160 17000
Trying 10.10.20.160...
telnet: Unable to connect to remote host: Connection refused
2018-05-16T21:55:51: %AETEST-INFO: STEP 1: Connecting to Router-1 - Errored
2018-05-16T21:55:51: %AETEST-ERROR: Caught exception during execution:
2018-05-16T21:55:51: %AETEST-ERROR: Traceback (most recent call last):
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/statemachine/statemachine.py", line 683, in unicon.statemachine.statemachine.StateMachine.go_to
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/statemachine/statetransition.py", line 479, in unicon.statemachine.statetransition.AnyStateTransition.do_transitions
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/eal/dialogs.py", line 408, in unicon.eal.dialogs.Dialog.process
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/eal/dialog_processor.py", line 656, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.process
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/eal/dialog_processor.py", line 641, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.process
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/eal/dialog_processor.py", line 554, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.expect_eval_statements
2018-05-16T21:55:51: %AETEST-ERROR:   File "/usr/local/lib/python3.6/site-packages/unicon/plugins/generic/statements.py", line 29, in connection_refused_handler
2018-05-16T21:55:51: %AETEST-ERROR:     raise Exception('Connection refused to device %s' % (str(spawn),))
2018-05-16T21:55:51: %AETEST-ERROR: Exception: Connection refused to device spawn_command: telnet 10.10.20.160 17000, id: 140354860417544
2018-05-16T21:55:51: %AETEST-ERROR:
2018-05-16T21:55:51: %AETEST-ERROR: The above exception was the direct cause of the following exception:
2018-05-16T21:55:51: %AETEST-ERROR:
2018-05-16T21:55:51: %AETEST-ERROR: Traceback (most recent call last):
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/bases/connection.py", line 419, in unicon.bases.connection.Connection.connect
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/bases/routers/connection_provider.py", line 146, in unicon.bases.routers.connection_provider.BaseSingleRpConnectionProvider.connect
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/bases/routers/connection_provider.py", line 167, in unicon.bases.routers.connection_provider.BaseSingleRpConnectionProvider.establish_connection
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/statemachine/statemachine.py", line 686, in unicon.statemachine.statemachine.StateMachine.go_to
2018-05-16T21:55:51: %AETEST-ERROR: unicon.core.errors.StateMachineError: Failed while bringing device to "any" state
2018-05-16T21:55:51: %AETEST-ERROR:
2018-05-16T21:55:51: %AETEST-ERROR: The above exception was the direct cause of the following exception:
2018-05-16T21:55:51: %AETEST-ERROR:
2018-05-16T21:55:51: %AETEST-ERROR: Traceback (most recent call last):
2018-05-16T21:55:51: %AETEST-ERROR:   File "/tests/pyats_ios_example.py", line 132, in establish_connections
2018-05-16T21:55:51: %AETEST-ERROR:     ios1.connect()
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/ats/connections/manager.py", line 283, in ats.connections.manager.ConnectionManager.connect
2018-05-16T21:55:51: %AETEST-ERROR:   File "src/unicon/bases/connection.py", line 423, in unicon.bases.connection.Connection.connect
2018-05-16T21:55:51: %AETEST-ERROR: unicon.core.errors.ConnectionError: failed to connect to ios1
2018-05-16T21:55:51: %AETEST-INFO: +----------------------------------------------------------+
2018-05-16T21:55:51: %AETEST-INFO: |                       STEPS Report                       |
2018-05-16T21:55:51: %AETEST-INFO: +----------------------------------------------------------+
2018-05-16T21:55:51: %AETEST-INFO: STEP 1 - Connecting to Router-1                      Errored
2018-05-16T21:55:51: %AETEST-INFO: ------------------------------------------------------------
2018-05-16T21:55:51: %AETEST-INFO: The result of subsection establish_connections is => ERRORED
2018-05-16T21:55:52: %AETEST-INFO: Starting subsection marking_interface_count_testcases
2018-05-16T21:55:52: %SCRIPT-INFO: +------------------------------------------------------------------------------+
2018-05-16T21:55:52: %SCRIPT-INFO: |          Looping VerifyInterfaceCountTestcase for ['ios1', 'ios2']           |
2018-05-16T21:55:52: %SCRIPT-INFO: +------------------------------------------------------------------------------+
2018-05-16T21:55:52: %AETEST-INFO: The result of subsection marking_interface_count_testcases is => PASSED
2018-05-16T21:55:52: %AETEST-INFO: The result of common setup is => ERRORED
2018-05-16T21:55:52: %AETEST-INFO: Starting testcase PingTestcase[device=ios1]
2018-05-16T21:55:52: %AETEST-INFO: Blocking PingTestcase[device=ios1] because common_setup did not pass.
2018-05-16T21:55:52: %AETEST-INFO: The result of testcase PingTestcase[device=ios1] is => BLOCKED
2018-05-16T21:55:52: %AETEST-INFO: Starting testcase PingTestcase[device=ios2]
2018-05-16T21:55:52: %AETEST-INFO: Blocking PingTestcase[device=ios2] because common_setup did not pass.
2018-05-16T21:55:52: %AETEST-INFO: The result of testcase PingTestcase[device=ios2] is => BLOCKED
2018-05-16T21:55:52: %AETEST-INFO: Starting testcase VerifyInterfaceCountTestcase[device=ios1]
2018-05-16T21:55:52: %AETEST-INFO: Blocking VerifyInterfaceCountTestcase[device=ios1] because common_setup did not pass.
2018-05-16T21:55:52: %AETEST-INFO: The result of testcase VerifyInterfaceCountTestcase[device=ios1] is => BLOCKED
2018-05-16T21:55:52: %AETEST-INFO: Starting testcase VerifyInterfaceCountTestcase[device=ios2]
2018-05-16T21:55:52: %AETEST-INFO: Blocking VerifyInterfaceCountTestcase[device=ios2] because common_setup did not pass.
2018-05-16T21:55:52: %AETEST-INFO: The result of testcase VerifyInterfaceCountTestcase[device=ios2] is => BLOCKED
2018-05-16T21:55:52: %AETEST-INFO: Starting common cleanup
2018-05-16T21:55:52: %AETEST-INFO: Starting subsection disconnect
2018-05-16T21:55:52: %AETEST-INFO: STEP 1: Disconnecting from Router-1
2018-05-16T21:56:04: %AETEST-INFO: STEP 1: Disconnecting from Router-1 - Passed
2018-05-16T21:56:04: %AETEST-INFO: STEP 2: Disconnecting from Router-2
2018-05-16T21:56:04: %AETEST-INFO: STEP 2: Disconnecting from Router-2 - Passed
2018-05-16T21:56:04: %AETEST-ERROR: Caught exception during execution:
2018-05-16T21:56:04: %AETEST-ERROR: Traceback (most recent call last):
2018-05-16T21:56:04: %AETEST-ERROR:   File "/tests/pyats_ios_example.py", line 352, in disconnect
2018-05-16T21:56:04: %AETEST-ERROR:     if ios1.connected or ios2.connected:
2018-05-16T21:56:04: %AETEST-ERROR:   File "src/ats/topology/device.py", line 439, in ats.topology.device.Device.__getattr__
2018-05-16T21:56:04: %AETEST-ERROR: AttributeError: 'Device' object has no attribute 'connected'
2018-05-16T21:56:04: %AETEST-INFO: +----------------------------------------------------------+
2018-05-16T21:56:04: %AETEST-INFO: |                       STEPS Report                       |
2018-05-16T21:56:04: %AETEST-INFO: +----------------------------------------------------------+
2018-05-16T21:56:04: %AETEST-INFO: STEP 1 - Disconnecting from Router-1                  Passed
2018-05-16T21:56:04: %AETEST-INFO: STEP 2 - Disconnecting from Router-2                  Passed
2018-05-16T21:56:04: %AETEST-INFO: ------------------------------------------------------------
2018-05-16T21:56:04: %AETEST-INFO: The result of subsection disconnect is => ERRORED
2018-05-16T21:56:04: %AETEST-INFO: The result of common cleanup is => ERRORED
2018-05-16T21:56:04: %EASYPY-INFO: --------------------------------------------------------------------------------
2018-05-16T21:56:04: %EASYPY-INFO: Job finished. Wrapping up...
2018-05-16T21:56:04: %EASYPY-INFO: Creating archive file: /tests/.pyATS/18-May/pyats_ios_example_job.2018May16_21:55:39.zip
2018-05-16T21:56:04: %EASYPY-INFO: +------------------------------------------------------------------------------+
2018-05-16T21:56:04: %EASYPY-INFO: |                                Easypy Report                                 |
2018-05-16T21:56:04: %EASYPY-INFO: +------------------------------------------------------------------------------+
2018-05-16T21:56:04: %EASYPY-INFO: pyATS Instance   : /usr/local
2018-05-16T21:56:04: %EASYPY-INFO: Python Version   : cpython-3.6.5 (64bit)
2018-05-16T21:56:04: %EASYPY-INFO: CLI Arguments    : /usr/local/bin/easypy /tests/pyats_ios_example_job.py -testbed_file /tests/default_testbed.yaml -archive_dir=/tests/.pyATS
2018-05-16T21:56:04: %EASYPY-INFO: User             : root
2018-05-16T21:56:04: %EASYPY-INFO: Host Server      : a40693bfc1dc
2018-05-16T21:56:04: %EASYPY-INFO: Host OS Version  : debian 8.10  (x86_64)
2018-05-16T21:56:04: %EASYPY-INFO:
2018-05-16T21:56:04: %EASYPY-INFO: Job Information
2018-05-16T21:56:04: %EASYPY-INFO:     Name         : pyats_ios_example_job
2018-05-16T21:56:04: %EASYPY-INFO:     Start time   : 2018-05-16 21:55:40.621092
2018-05-16T21:56:04: %EASYPY-INFO:     Stop time    : 2018-05-16 21:56:04.229015
2018-05-16T21:56:04: %EASYPY-INFO:     Elapsed time : 0:00:23.607923
2018-05-16T21:56:04: %EASYPY-INFO:     Archive      : /tests/.pyATS/18-May/pyats_ios_example_job.2018May16_21:55:39.zip
2018-05-16T21:56:04: %EASYPY-INFO:
2018-05-16T21:56:04: %EASYPY-INFO: Total Tasks    : 1
2018-05-16T21:56:04: %EASYPY-INFO:
2018-05-16T21:56:04: %EASYPY-INFO: Overall Stats
2018-05-16T21:56:04: %EASYPY-INFO:     Passed     : 0
2018-05-16T21:56:04: %EASYPY-INFO:     Passx      : 0
2018-05-16T21:56:04: %EASYPY-INFO:     Failed     : 0
2018-05-16T21:56:04: %EASYPY-INFO:     Aborted    : 0
2018-05-16T21:56:04: %EASYPY-INFO:     Blocked    : 4
2018-05-16T21:56:04: %EASYPY-INFO:     Skipped    : 0
2018-05-16T21:56:04: %EASYPY-INFO:     Errored    : 2
2018-05-16T21:56:04: %EASYPY-INFO:
2018-05-16T21:56:04: %EASYPY-INFO:     TOTAL      : 6
2018-05-16T21:56:04: %EASYPY-INFO:
2018-05-16T21:56:04: %EASYPY-INFO: Success Rate   : 0.00 %
2018-05-16T21:56:04: %EASYPY-INFO:
2018-05-16T21:56:04: %EASYPY-INFO: +------------------------------------------------------------------------------+
2018-05-16T21:56:04: %EASYPY-INFO: |                             Task Result Summary                              |
2018-05-16T21:56:04: %EASYPY-INFO: +------------------------------------------------------------------------------+
2018-05-16T21:56:04: %EASYPY-INFO: __task1: pyats_ios_example.commonSetup                                   ERRORED
2018-05-16T21:56:04: %EASYPY-INFO: __task1: pyats_ios_example.PingTestcase[device=ios1]                     BLOCKED
2018-05-16T21:56:04: %EASYPY-INFO: __task1: pyats_ios_example.PingTestcase[device=ios2]                     BLOCKED
2018-05-16T21:56:04: %EASYPY-INFO: __task1: pyats_ios_example.VerifyInterfaceCountTestcase[device=ios1]     BLOCKED
2018-05-16T21:56:04: %EASYPY-INFO: __task1: pyats_ios_example.VerifyInterfaceCountTestcase[device=ios2]     BLOCKED
2018-05-16T21:56:04: %EASYPY-INFO: __task1: pyats_ios_example.commonCleanup                                 ERRORED
2018-05-16T21:56:04: %EASYPY-INFO:
2018-05-16T21:56:04: %EASYPY-INFO: +------------------------------------------------------------------------------+
2018-05-16T21:56:04: %EASYPY-INFO: |                             Task Result Details                              |
2018-05-16T21:56:04: %EASYPY-INFO: +------------------------------------------------------------------------------+
2018-05-16T21:56:04: %EASYPY-INFO: __task1: pyats_ios_example
2018-05-16T21:56:04: %EASYPY-INFO: |-- commonSetup                                                          ERRORED
2018-05-16T21:56:04: %EASYPY-INFO: |   |-- check_topology                                                    PASSED
2018-05-16T21:56:04: %EASYPY-INFO: |   |-- establish_connections                                            ERRORED
2018-05-16T21:56:04: %EASYPY-INFO: |   |   `-- Step 1: Connecting to Router-1                               ERRORED
2018-05-16T21:56:04: %EASYPY-INFO: |   `-- marking_interface_count_testcases                                 PASSED
2018-05-16T21:56:04: %EASYPY-INFO: |-- PingTestcase[device=ios1]                                            BLOCKED
2018-05-16T21:56:04: %EASYPY-INFO: |-- PingTestcase[device=ios2]                                            BLOCKED
2018-05-16T21:56:04: %EASYPY-INFO: |-- VerifyInterfaceCountTestcase[device=ios1]                            BLOCKED
2018-05-16T21:56:04: %EASYPY-INFO: |-- VerifyInterfaceCountTestcase[device=ios2]                            BLOCKED
2018-05-16T21:56:04: %EASYPY-INFO: `-- commonCleanup                                                        ERRORED
2018-05-16T21:56:04: %EASYPY-INFO:     `-- disconnect                                                       ERRORED
2018-05-16T21:56:04: %EASYPY-INFO:         |-- Step 1: Disconnecting from Router-1                           PASSED
2018-05-16T21:56:04: %EASYPY-INFO:         `-- Step 2: Disconnecting from Router-2                           PASSED
2018-05-16T21:56:04: %EASYPY-INFO: No SMTP server information configured, ignoring sending notification email.
2018-05-16T21:56:04: %EASYPY-INFO: Done!
make: *** [test] Error 1
```
