### ISSUE TITLE
Trigger - TriggerShutNoShutBgp failing

### ISSUE THREAD

**Issue by RunSi** [CiscoDevNet/pyats-labs#15]
The genie_script.robot, genie_triggers.robot and genie_pts.robot are failing with the same exception relating to the trigger TriggerShuNoShutBgp.  I can confirm that the test topology is working correctly as genie_connect.robot and genie_sample.py  work fine (no dependency on TriggerShutNoShutBgp).

The following traceback is reported:

`[ ERROR ] Failed reason: Issue verifying the states                           
ops.bgp.bgp.Bgp - {'attributes': ['info']}:

Traceback (most recent call last):
  File "src/genie/ops/base/base.py", line 264, in genie.ops.base.base.Base._poll
  File "/usr/local/lib/python3.6/site-packages/genie/libs/sdk/libs/utils/mapping.py", line 392, in _verify_finds_ops
    self._verify_find(ops, [req], missing, all_keys)
  File "/usr/local/lib/python3.6/site-packages/genie/libs/sdk/libs/utils/mapping.py", line 376, in _verify_find
    "'{o}'".format(req=requirements, o=ops))
Exception: '[['info', 'instance', 'default', 'vrf', 'default', 'neighbor', '10.1.1.1', 'session_state', 'shut (admin)']]' does not exists in '<Bgp object at 0x7fee98bcc320>'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/genie/libs/sdk/libs/utils/mapping.py", line 519, in verify_ops
    requirements)
  File "/usr/local/lib/python3.6/site-packages/genie/libs/sdk/libs/utils/mapping.py", line 574, in _verify_ops
    raise e
  File "/usr/local/lib/python3.6/site-packages/genie/libs/sdk/libs/utils/mapping.py", line 569, in _verify_ops
    org_req=requirements)
  File "src/genie/ops/base/base.py", line 222, in genie.ops.base.base.Base.learn_poll
  File "src/genie/ops/base/base.py", line 254, in genie.ops.base.base.Base._learn_poll_timeout
StopIteration: Maximum amount of retries to learn <Bgp object at 0x7fee98bcc320>
`

**Comment by lubnarasheed** [comment]
fixed in pull #17
